name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily at 00:00 UTC
  workflow_dispatch:       # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake SVG / GIF
        uses: Platane/snk@v3
        with:
          github_user_name: Nazmul7989
          # You can output multiple formats
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif

      # Publish to the 'gh-pages' branch (recommended)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
